# Generated by Django 3.0.4 on 2020-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('date', models.DateTimeField()),
                ('photo', models.TextField()),
            ],
        ),
    ]
