# Generated by Django 3.0.4 on 2020-04-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probn', '0004_news3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='News1',
        ),
        migrations.DeleteModel(
            name='News2',
        ),
    ]
