# Generated by Django 3.1.3 on 2020-12-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201222_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='price_per',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.productinbasket'),
        ),
    ]
