# Generated by Django 3.1.3 on 2020-12-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productinorder_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
    ]
