# Generated by Django 3.0.4 on 2020-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tovar',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tovar',
            name='type',
            field=models.CharField(blank=True, default='kirpich', max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=500, upload_to='media/'),
        ),
    ]
